
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/new_schema?useSSL=false&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    servlet:
      multipart:
        enabled: true
        max-file-size: 20MB
        max-request-size: 20MB


  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        cache:
          use_second_level_cache: false
          cache:
            use_query_cache: false
        dialect: org.hibernate.dialect.MySQLDialect
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


fileRepositoryFolder: /home/pammaturo/Immagini/