CREATE TABLE utente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    nome_utente VARCHAR(255),
    immagine_profilo VARCHAR(500),
    ce VARCHAR(255),
    tipo_utenza VARCHAR(15) NOT NULL
);

CREATE TABLE libro (
    id_libro BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_utente BIGINT NOT NULL,
    titolo VARCHAR(255) NOT NULL,
    autore VARCHAR(255) NOT NULL,
    copertina VARCHAR(500),
    ce VARCHAR(255),
    media_voti DOUBLE,
    CONSTRAINT fk_libro_utente FOREIGN KEY (id_utente) REFERENCES utente(id)
);

CREATE TABLE libriletti (
    id_libri_letti BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_libroll BIGINT NOT NULL,
    id_utentell BIGINT NOT NULL,
    voto BIGINT,
    CONSTRAINT fk_libriletti_utente FOREIGN KEY (id_utentell) REFERENCES utente(id),
    CONSTRAINT fk_libriletti_libro FOREIGN KEY (id_libroll) REFERENCES libro(id_libro)
);

CREATE TABLE listadesideri (
    id_lista_desideri BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_utenteld BIGINT NOT NULL,
    id_librold BIGINT NOT NULL,
    CONSTRAINT fk_listadesideri_utente FOREIGN KEY (id_utenteld) REFERENCES utente(id),
    CONSTRAINT fk_listadesideri_libro FOREIGN KEY (id_librold) REFERENCES libro(id_libro)
);